CREATE TABLE ORDER_DETAIL

(
    ORDER_DETAIL_ID NUMBER(10),
    ORDER_ID NUMBER(10) UNIQUE NOT NULL,
    CREATED_DATE DATE NOT NULL,
    EXAMINE_DATE DATE NOT NULL,
    PRICE NUMBER(10,2) NOT NULL,
    ORDER_DAY NUMBER (3) NOT NULL,
    STATUS_ID NUMBER(10) NOT NULL,
    
    
    CONSTRAINT PK_ORDER_DETAIL_ID
    PRIMARY KEY (ORDER_DETAIL_ID),
    
    CONSTRAINT FK_ORDER_DETAIL_ORDER_ID
    FOREIGN KEY(ORDER_ID) REFERENCES CUSTOMER_ORDER(ORDER_ID)
    ON DELETE CASCADE,
    
    CONSTRAINT FK_ORDER_DETAIL_ORDER_STATUS_ID
    FOREIGN KEY(STATUS_ID) REFERENCES ORDER_STATUS(ORDER_STATUS_ID)
    ON DELETE CASCADE

);