CREATE TABLE CUSTOMER_ORDER 
(
    ORDER_ID NUMBER(10) ,
    CAR_ID NUMBER(10) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    PICK_UP_DATE DATE NOT NULL,
    RETURN_DATE DATE NOT NULL,
    
    
    CONSTRAINT PK_ORDER_ID
    PRIMARY KEY (ORDER_ID),
    
    CONSTRAINT FK_ORDER_CAR_ID
    FOREIGN KEY (CAR_ID) REFERENCES CAR (CAR_ID),
    
    CONSTRAINT FK_ORDER_CUSTOMER_ID
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
    
    --CHECK PICUPDATE < SYS.DATE.NOW
)