 CREATE OR REPLACE PROCEDURE INSERT_CAR 
 (
    P_PLATE       IN CAR.PLATE%TYPE,
    P_CLASS       IN CAR.CAR_CLASS%TYPE,
    P_FUEL        IN CAR.FUEL_TYPE%TYPE,
    P_GEAR        IN CAR.GEAR_TYPE%TYPE,
    P_MODEL       IN CAR_INFO.CAR_MODEL%TYPE,
    P_NAME        IN CAR_INFO.CAR_NAME%TYPE,
    P_YEAR        IN CAR_INFO.CAR_YEAR%TYPE,
    P_KILOMETER   IN CAR_INFO.CAR_KILOMETER%TYPE

 )
 
 IS
 
    P_CAR_ID NUMBER;
 BEGIN
        
        INSERT INTO CAR ("PLATE","CAR_CLASS","FUEL_TYPE","GEAR_TYPE")
        VALUES (P_PLATE,P_CLASS,P_FUEL,P_GEAR);
        
        P_CAR_ID :=FINDCARBYPLATE(P_PLATE);
        
        INSERT INTO CAR_INFO ("CAR_ID","CAR_MODEL","CAR_NAME","CAR_YEAR","CAR_KILOMETER")
        VALUES (P_CAR_ID,P_MODEL,P_NAME,P_YEAR,P_KILOMETER);
        
        
            DBMS_OUTPUT.PUT_LINE('PLATE :' || P_PLATE);
            DBMS_OUTPUT.PUT_LINE('CAR CLASS :' || P_CLASS);
            DBMS_OUTPUT.PUT_LINE('FUEL TYPE :' || P_FUEL);
            DBMS_OUTPUT.PUT_LINE('GEAR TYPE :' || P_GEAR);
            DBMS_OUTPUT.PUT_LINE('MODEL :' || P_MODEL);
            DBMS_OUTPUT.PUT_LINE('NAME :' || P_NAME);
            DBMS_OUTPUT.PUT_LINE('YEAR :' || P_YEAR);
            DBMS_OUTPUT.PUT_LINE('KILOMETER :' || P_KILOMETER);
            
             DBMS_OUTPUT.PUT_LINE('Car and car info rows inserted.');
 END;
 