CREATE OR REPLACE VIEW CUSTOMER_WITH_ALL_DETAIL AS
    SELECT CUSTOMER.FIRST_NAME,CUSTOMER.LAST_NAME,CUSTOMER.IDENTITY_NUMBER, CUSTOMER.BIRTHDAY , CUSTOMER_ADRESS.COUNTRY, CUSTOMER_ADRESS.CITY, CUSTOMER_ADRESS.TOWN
    ,CUSTOMER_ADRESS.STREET ,CUSTOMER_ADRESS.BUILDING_INFO,CUSTOMER_ADRESS.DOOR_NUMBER, CUSTOMER_ADRESS.ZIP_CODE, CUSTOMER_LOGIN.CREATED_DATE , CUSTOMER_LOGIN.EMAIL
    FROM CUSTOMER 
    INNER JOIN CUSTOMER_ADRESS
    ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ADRESS.CUSTOMER_ID
    INNER JOIN CUSTOMER_LOGIN
    ON CUSTOMER.LOGIN_ID = CUSTOMER_LOGIN.LOGIN_ID;