CREATE TABLE DELETED_CUSTOMER_LOGIN AS (SELECT * FROM CUSTOMER_ADRESS);
CREATE TABLE DELETED_CUSTOMER AS (SELECT * FROM CUSTOMER_ADRESS);
CREATE TABLE DELETED_CUSTOMER_ADRESS AS (SELECT * FROM CUSTOMER_ADRESS);
CREATE TABLE DELETED_CREDIT_CARD AS (SELECT * FROM CREDIT_CARD);
CREATE TABLE DELETED_DRIVE_LICENCE AS (SELECT * FROM DRIVE_LICENCE);