create or replace procedure P_ADD_CUSTOMER
(
P_EMAIL CUSTOMER_LOGIN.EMAIL%type,
P_PASSWORD CUSTOMER_LOGIN.CUSTOMER_PASSWORD%type,
P_FIRSTNAME CUSTOMER.FIRST_NAME%type,
P_LASTNAME CUSTOMER.LAST_NAME%type,
P_IDENTITY_NUMBER CUSTOMER.IDENTITY_NUMBER%type,
P_BIRTHDAY CUSTOMER.BIRTHDAY%type,
P_COUNTRY CUSTOMER_ADRESS.COUNTRY%type,
P_CITY CUSTOMER_ADRESS.CITY%type,
P_TOWN CUSTOMER_ADRESS.TOWN%type,
P_STREET CUSTOMER_ADRESS.STREET%type,
P_BULDING CUSTOMER_ADRESS.BUILDING_INFO%type,
P_DOOR_NUMBER CUSTOMER_ADRESS.DOOR_NUMBER%type,
P_ZIP_CODE CUSTOMER_ADRESS.ZIP_CODE%type
)


is
    P_CUSTOMER_LOGIN_ID CUSTOMER_LOGIN.LOGIN_ID%type;
    P_CUSTOMER_ID number;
begin

    insert into CUSTOMER_LOGIN ("EMAIL","CUSTOMER_PASSWORD") values (P_EMAIL,P_PASSWORD);
    P_CUSTOMER_LOGIN_ID := GETCUSTOMERBYEMAIL(P_EMAIL);
    
    if p_customer_login_id is not null  then
    insert into CUSTOMER ("LOGIN_ID","FIRST_NAME","LAST_NAME","IDENTITY_NUMBER","BIRTHDAY")
    values (P_CUSTOMER_LOGIN_ID,P_FIRSTNAME,P_LASTNAME,P_IDENTITY_NUMBER,P_BIRTHDAY);
    P_CUSTOMER_ID := GETCUSTOMERBYIDENTITYNUMBER(P_IDENTITY_NUMBER);
    end if;
    
    
    if p_customer_id is not null then
    insert into CUSTOMER_ADRESS ("CUSTOMER_ID","COUNTRY","CITY","TOWN","STREET","BUILDING_INFO","DOOR_NUMBER","ZIP_CODE")
    values (P_CUSTOMER_ID,P_COUNTRY,P_CITY,P_TOWN,P_STREET,P_BULDING,P_DOOR_NUMBER,P_ZIP_CODE);
    end if;
    
    
    DBMS_OUTPUT.PUT_LINE('E-MAIL :' || P_EMAIL);
    DBMS_OUTPUT.PUT_LINE('PASSWORD :' || P_PASSWORD);
    DBMS_OUTPUT.PUT_LINE('FIRSTNAME :' || P_FIRSTNAME);
    DBMS_OUTPUT.PUT_LINE('LASTNAME :' || P_LASTNAME);
    DBMS_OUTPUT.PUT_LINE('IDENTITY NUMBER :' || P_IDENTITY_NUMBER); 
    DBMS_OUTPUT.PUT_LINE('BIRTHDAY :' || P_BIRTHDAY);
    DBMS_OUTPUT.PUT_LINE('COUNTRY :' || P_COUNTRY);
    DBMS_OUTPUT.PUT_LINE('CITY :' || P_CITY);
    DBMS_OUTPUT.PUT_LINE('TOWN :' || P_TOWN);
    DBMS_OUTPUT.PUT_LINE('STREET :' || P_STREET);
    DBMS_OUTPUT.PUT_LINE('BUILDING INFO :' || P_BULDING);
    DBMS_OUTPUT.PUT_LINE('DOOR NUMBER:' || P_DOOR_NUMBER);
    DBMS_OUTPUT.PUT_LINE('ZIP CODE:' || P_ZIP_CODE);
    
    
end;